version: '2'
services:
  #PHP_PHP-FPM_NGINX
  ezy_server:
    build: ./server
    container_name: ezy_server
    volumes:
      - ../:/var/www/project
    ports:
      - "8010:80"
  #MYSQL
  ezy_mysql:
    container_name: ezy_mysql
    build: ./mysql
    tty: true
    ports:
      - "13306:3306"
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root@secret123
  #REDIS
  # ezy_redis:
  #   build: ./redis
